---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ps-nw-test-server
  labels:
    app.kubernetes.io/name: ps-nw-test-server
    app.kubernetes.io/part-of: ps-nw-test-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ps-nw-test-server
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ps-nw-test-server
    spec:
      containers:
      - name: app
        image: pasientskyhosting/ps-nw-test
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ps-nw-test-server
    app.kubernetes.io/part-of: ps-nw-test-server
  name: ps-nw-test-server
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: ps-nw-test-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ps-nw-test-client
  labels:
    app.kubernetes.io/name: ps-nw-test-client
    app.kubernetes.io/part-of: ps-nw-test-client
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ps-nw-test-client
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ps-nw-test-client
    spec:
      containers:
      - name: app
        image: pasientskyhosting/ps-nw-test
